/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestIntentionDetection */

#ifndef _Included_TestIntentionDetection
#define _Included_TestIntentionDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestIntentionDetection
 * Method:    setCallback
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_TestIntentionDetection_setCallback
  (JNIEnv *, jobject);

/*
 * Class:     TestIntentionDetection
 * Method:    sendMessage
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_TestIntentionDetection_sendMessage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     TestIntentionDetection
 * Method:    getCurrentSituation
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestIntentionDetection_getCurrentSituation
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
